apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-facts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planet-facts
  template:
    metadata:
      labels:
        app: planet-facts
    spec:
      containers:
      - name: planet-facts
        image: <aws_account_id>.dkr.ecr.<your-region>.amazonaws.com/planet-facts-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: planet-facts-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: planet-facts
